#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import struct
from pathlib import Path


MAGIC = b"HSONTR1\0"


def sanitize_value(value: str) -> str:
    return (
        value.replace("\r\n", "#n")
        .replace("\r", "#r")
        .replace("\n", "#n")
        .replace("\t", "#t")
        .replace("\x00", "")
    )


def find_translation_object(source: str) -> str:
    marker = "var translation_default = "
    start = source.find(marker)
    if start < 0:
        start = 0
    else:
        start += len(marker)
    while start < len(source) and source[start].isspace():
        start += 1
    if start >= len(source) or source[start] != "{":
        raise SystemExit("Could not find translation JSON object")

    depth = 0
    in_string = False
    escaped = False
    quote = ""
    for index in range(start, len(source)):
        ch = source[index]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == quote:
                in_string = False
            continue
        if ch in ('"', "'"):
            in_string = True
            quote = ch
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return source[start : index + 1]
    raise SystemExit("Could not find end of translation_default object")


def make_blob(data: dict[str, str]) -> tuple[bytes, int]:
    out = bytearray(MAGIC)
    sanitized = 0
    items = []
    for key, value in data.items():
        text = str(value)
        safe = sanitize_value(text)
        if safe != text:
            sanitized += 1
        items.append((str(key), safe))
    items.sort(key=lambda item: item[0])
    out.extend(struct.pack("<I", len(items)))
    for key, value in items:
        kb = key.encode("utf-8")
        vb = value.encode("utf-8")
        out.extend(struct.pack("<II", len(kb), len(vb)))
        out.extend(kb)
        out.extend(vb)
    return bytes(out), sanitized


def write_cpp(blob: bytes, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by make_translation_blob_cpp.py",
        "#include <stdint.h>",
        'extern "C" {',
        "__attribute__((visibility(\"default\")))",
        f"extern const uint8_t animegame_translation_blob[{len(blob)}] = {{",
    ]
    for i in range(0, len(blob), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in blob[i : i + 16])
        lines.append(f"  {chunk},")
    lines += [
        "};",
        "__attribute__((visibility(\"default\")))",
        f"extern const uint8_t *animegame_translation_blob_end = animegame_translation_blob + {len(blob)};",
        "}",
        "",
    ]
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("g_js", type=Path)
    parser.add_argument("output_cpp", type=Path)
    parser.add_argument("--blob-out", type=Path)
    args = parser.parse_args()

    source = args.g_js.read_text("utf-8")
    data = json.loads(find_translation_object(source))
    if not isinstance(data, dict):
        raise SystemExit("translation_default did not decode as an object")
    blob, sanitized = make_blob({str(k): str(v) for k, v in data.items()})
    write_cpp(blob, args.output_cpp)
    if args.blob_out:
        args.blob_out.parent.mkdir(parents=True, exist_ok=True)
        args.blob_out.write_bytes(blob)
    print(f"entries={len(data)}")
    print(f"sanitized={sanitized}")
    print(f"blob_size={len(blob)}")
    print(f"sha256={hashlib.sha256(blob).hexdigest()}")
    print(f"cpp={args.output_cpp}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
